//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EdTech.Data.AlphaSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public int Id { get; set; }
        public string ZipCode1 { get; set; }
        public string ZipType { get; set; }
        public string City { get; set; }
        public string CityType { get; set; }
        public string State { get; set; }
        public string StateAbbr { get; set; }
        public string AreaCode { get; set; }
        public double Latitude { get; set; }
        public double Longitude { get; set; }
    }
}
